#!/usr/bin/env zsh
# install.zsh — Install or update zsh config from this repo to ZDOTDIR
set -euo pipefail

# ---------------------------------------------------------------------------
# Platform detection
# ---------------------------------------------------------------------------
detect_platform() {
  case "$(uname -s)" in
    Darwin) echo "macos" ;;
    Linux)  echo "linux" ;;
    *)      echo "unknown" ;;
  esac
}

PLATFORM=$(detect_platform)

if [[ "$PLATFORM" == "unknown" ]]; then
  print -P "%F{red}error:%f unsupported platform: $(uname -s)" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Resolve paths
# ---------------------------------------------------------------------------
REPO_DIR="${0:A:h}"   # absolute dir of this script (zsh :A:h expansion)

TARGET_DIR="${1:-${XDG_CONFIG_HOME:-$HOME/.config}/zsh}"

# ---------------------------------------------------------------------------
# macOS: install dependencies
# ---------------------------------------------------------------------------
install_macos_deps() {
  echo ""
  print -P "%F{blue}==> Dependencies%f"

  # Homebrew
  if ! command -v brew &>/dev/null; then
    echo "  installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # The installer doesn't update PATH for the current session — do it manually
    if [[ -x /opt/homebrew/bin/brew ]]; then
      eval "$(/opt/homebrew/bin/brew shellenv)"   # Apple Silicon
    elif [[ -x /usr/local/bin/brew ]]; then
      eval "$(/usr/local/bin/brew shellenv)"       # Intel
    fi
  else
    echo "  ok      Homebrew"
  fi

  # CLI tools
  local formulae=(antidote fzf)
  for pkg in "${formulae[@]}"; do
    if brew list --formula "$pkg" &>/dev/null; then
      echo "  ok      $pkg"
    else
      echo "  installing $pkg..."
      brew install "$pkg"
    fi
  done

  # Nerd Font for Powerlevel10k
  local cask="font-meslo-for-powerlevel10k"
  if brew list --cask "$cask" &>/dev/null; then
    echo "  ok      $cask"
  else
    echo "  installing $cask..."
    brew install --cask "$cask"
  fi

  # Suppress "Last login" banner
  if [[ ! -f "$HOME/.hushlogin" ]]; then
    touch "$HOME/.hushlogin"
    echo "  created ~/.hushlogin"
  else
    echo "  ok      ~/.hushlogin"
  fi
}

# ---------------------------------------------------------------------------
# Copy config files (atomic: stage to temp dir, then move into place)
# ---------------------------------------------------------------------------
install_config_files() {
  if [[ "$REPO_DIR" == "$TARGET_DIR" ]]; then
    echo ""
    echo "Repo is already at target ($TARGET_DIR) — skipping file copy."
    return
  fi

  if ! git -C "$REPO_DIR" rev-parse --git-dir &>/dev/null; then
    print -P "%F{red}error:%f $REPO_DIR is not a git repository" >&2
    exit 1
  fi

  echo ""
  print -P "%F{blue}==> Config files%f"
  echo "  repo:   $REPO_DIR"
  echo "  target: $TARGET_DIR"
  echo ""

  TRACKED_FILES=("${(@f)$(git -C "$REPO_DIR" ls-files)}")

  # Stage all copies into a temp dir first — if anything fails we don't
  # touch the live target at all.
  local stage
  stage=$(mktemp -d)
  trap "rm -rf ${(q)stage}" EXIT

  for rel in "${TRACKED_FILES[@]}"; do
    case "$rel" in
      install.zsh|README.md|.gitignore) continue ;;
    esac
    local stage_dst="$stage/$rel"
    [[ -d "${stage_dst:h}" ]] || mkdir -p "${stage_dst:h}"
    cp "$REPO_DIR/$rel" "$stage_dst"
  done

  # All copies succeeded — move staged files into target
  for rel in "${TRACKED_FILES[@]}"; do
    case "$rel" in
      install.zsh|README.md|.gitignore) continue ;;
    esac

    local src="$stage/$rel"
    local dst="$TARGET_DIR/$rel"

    [[ -d "${dst:h}" ]] || mkdir -p "${dst:h}"

    if [[ -e "$dst" ]]; then
      if diff -q "$src" "$dst" &>/dev/null; then
        echo "  ok      $rel"
        continue
      else
        echo "  update  $rel"
      fi
    else
      echo "  copy    $rel"
    fi

    mv "$src" "$dst"
  done
}

# ---------------------------------------------------------------------------
# Write ~/.zshenv bootstrap (must live outside ZDOTDIR)
# ---------------------------------------------------------------------------
install_zshenv() {
  echo ""
  print -P "%F{blue}==> ~/.zshenv bootstrap%f"

  local target="$HOME/.zshenv"
  local content
  content=$(printf '%s\n' \
    '#!/bin/zsh' \
    '#' \
    '# ~/.zshenv — bootstraps ZDOTDIR so Zsh finds the rest of the config.' \
    '# Generated by install.zsh — edit the original in $ZDOTDIR/.zshenv instead.' \
    '#' \
    '' \
    "export ZDOTDIR=\"$TARGET_DIR\"" \
    '' \
    'export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}' \
    'export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}' \
    'export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}' \
    'export ZDOTDIR=${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}' \
    '' \
    '[[ -r "$ZDOTDIR/.zshenv" ]] && source "$ZDOTDIR/.zshenv"' \
  )

  if [[ -f "$target" ]] && diff -q <(echo "$content") "$target" &>/dev/null; then
    echo "  ok      ~/.zshenv"
    return
  fi

  # Atomic write: stage beside target, then rename
  local tmp
  tmp=$(mktemp "${target}.XXXXXX")
  echo "$content" > "$tmp"

  if [[ -f "$target" ]]; then
    cp "$target" "${target}.bak"
    echo "  backup  ~/.zshenv.bak"
  fi

  mv "$tmp" "$target"
  echo "  written ~/.zshenv"
}

# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------
[[ "$PLATFORM" == "macos" ]] && install_macos_deps
install_config_files
install_zshenv

echo ""
print -P "%F{green}Done.%f"
[[ "$PLATFORM" == "macos" ]] && echo "Open a new terminal — p10k will launch its configuration wizard automatically."
